name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: ">=12.12.0"

    - run: npm install

    - name: ghpages
      run: |
        mkdir dist
        touch dist/.nojekyll
        echo sudoku.monster > dist/CNAME

    - name: Build
      run: env NODE_ENV=production npm run webpack

    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
